export type Page = "home"|"atlas"|"discover"|"packages"|"about"|"apps"|"wallet"|"bookings"|"household"|"offers"|"pricing"|"onboard"|"provider-apply"|"provider"|"provider-signin"|"admin"|"business"|"signin"|"ai-connect";
export type Service = {id:string;name:string;providerId:string;provider:string;category:string;mode:"At home"|"Virtual"|"Provider location"|"At hotel";area:string;price:number;standardPrice:number;duration:string;rating:number;reviews:number;next:string;description:string;clinical?:boolean;lawful?:string;source?:"demo"|"application"};
export type WeeklyAvailability = {dayOfWeek: number; start: string; end: string};
export type ProviderProfile = {id:string;name:string;initials:string;credential:string;focuses:string[];funFact:string;years:number;area:string;rating:number;reviews:number;next:string;serviceId:string;bio?:string;availability?:WeeklyAvailability[];source?:"demo"|"application"};
export type Booking = {id:string;serviceId:string;serviceName:string;provider:string;date:string;mode:string;credits:number;status:"Upcoming"|"Completed"|"Cancelled";packageName?:string;packageItem?:string;assignment?:"unassigned"|"accepted"|"proposed"|"declined";proposedDate?:string;source?:"web"|"mcp"|string};
export type PackageProduct = {id:string;name:string;price:number;expires:string;items:{label:string;count:number}[]};

export const services: Service[] = [
 {id:"sports-massage",name:"Sports Massage",providerId:"tide-tone",provider:"Tide & Tone Recovery",category:"Recovery",mode:"At home",area:"Miami Beach",price:150,standardPrice:150,duration:"60 min",rating:4.9,reviews:128,next:"Tomorrow · 7:30 PM",description:"Targeted massage delivered in the comfort of your home, tailored to active bodies and training schedules."},
 {id:"deep-tissue",name:"Deep Tissue Massage",providerId:"tide-tone",provider:"Tide & Tone Recovery",category:"Recovery",mode:"At home",area:"Miami-Dade",price:150,standardPrice:150,duration:"60 min",rating:4.9,reviews:96,next:"Today · 6:00 PM",description:"A firm, targeted massage session delivered by an independent provider in the comfort of your home."},
 {id:"stretch",name:"Assisted Stretching",providerId:"form-house",provider:"Form House Miami",category:"Recovery",mode:"At home",area:"Brickell",price:100,standardPrice:100,duration:"45 min",rating:4.8,reviews:74,next:"Tomorrow · 8:00 PM",description:"One-on-one guided mobility work brought to your home and shaped around your comfort and movement goals."},
 {id:"blood-draw",name:"Blood Tests",providerId:"harbor-dx",provider:"Harbor Diagnostics Partner",category:"Clinical",mode:"At home",area:"Miami-Dade",price:100,standardPrice:100,duration:"30 min",rating:4.7,reviews:42,next:"Monday · 8:00 AM",description:"At-home specimen collection by an independent qualified partner.",clinical:true,lawful:"Available when ordered or otherwise lawfully available through the clinical partner."},
 {id:"dietitian",name:"Registered Dietitian Consultation",providerId:"nourish-south",provider:"Nourish South",category:"Nutrition",mode:"Virtual",area:"Virtual",price:145,standardPrice:160,duration:"50 min",rating:4.9,reviews:61,next:"Today · 5:30 PM",description:"General nutrition support from an independent registered dietitian."},
 {id:"training",name:"Private Personal Training",providerId:"form-house",provider:"Form House Miami",category:"Fitness",mode:"At home",area:"Brickell",price:135,standardPrice:150,duration:"60 min",rating:4.8,reviews:88,next:"Friday · 7:00 AM",description:"A private strength and conditioning session shaped around your goals."},
 {id:"pilates",name:"Private Pilates",providerId:"casa-forma",provider:"Casa Forma",category:"Fitness",mode:"Provider location",area:"Coconut Grove",price:120,standardPrice:135,duration:"50 min",rating:4.9,reviews:105,next:"Saturday · 9:00 AM",description:"Private reformer Pilates in a calm, light-filled studio."},
 {id:"pt",name:"Physical Therapy Assessment",providerId:"marlin-pt",provider:"Marlin Movement PT",category:"Clinical wellness",mode:"Provider location",area:"Coral Gables",price:195,standardPrice:215,duration:"60 min",rating:4.9,reviews:52,next:"Friday · 11:00 AM",description:"An assessment performed by an independent licensed physical therapist.",clinical:true},
 {id:"whitening",name:"Teeth Whitening Appointment",providerId:"bright-house",provider:"Bright House Miami",category:"Personal care",mode:"Provider location",area:"Coral Gables",price:275,standardPrice:300,duration:"75 min",rating:4.7,reviews:45,next:"Thursday · 2:00 PM",description:"Cosmetic whitening performed by an appropriately qualified independent provider.",clinical:true},
 {id:"iv",name:"IV Drip",providerId:"palm-clinical",provider:"Palm Clinical Mobile",category:"Clinical",mode:"At home",area:"Miami Beach",price:125,standardPrice:125,duration:"60 min",rating:4.8,reviews:38,next:"Today · 4:45 PM",description:"A non-emergency clinical appointment with an independent qualified provider. Salu makes no efficacy claim.",clinical:true,lawful:"Subject to independent clinical screening and lawful provider availability."},
 {id:"nad",name:"NAD+ Drip",providerId:"palm-clinical",provider:"Palm Clinical Mobile",category:"Clinical",mode:"At home",area:"Miami-Dade",price:300,standardPrice:300,duration:"90 min",rating:4.8,reviews:24,next:"Tomorrow · 5:30 PM",description:"A non-emergency clinical appointment with an independent qualified provider. Salu makes no claim about the benefits or efficacy of NAD+ infusions.",clinical:true,lawful:"Subject to independent clinical screening and lawful provider availability."},
 {id:"acupuncture",name:"Acupuncture",providerId:"quiet-point",provider:"Quiet Point Miami",category:"Recovery",mode:"At home",area:"Miami-Dade",price:150,standardPrice:150,duration:"60 min",rating:4.9,reviews:37,next:"Friday · 4:00 PM",description:"An at-home acupuncture session delivered by an independent appropriately licensed provider. Salu makes no efficacy claim.",clinical:true,lawful:"Subject to independent provider screening and lawful availability."},
 {id:"lymphatic-massage",name:"Lymphatic Drainage Massage",providerId:"tide-tone",provider:"Tide & Tone Recovery",category:"Aesthetic",mode:"At home",area:"Miami-Dade",price:150,standardPrice:150,duration:"60 min",rating:4.8,reviews:54,next:"Tomorrow · 3:30 PM",description:"A gentle at-home massage experience delivered by an independent provider. Salu does not claim medical or therapeutic outcomes."},
 {id:"facial-workout",name:"Facial Workout Massage",providerId:"luma-mobile",provider:"Luma Mobile Skin",category:"Aesthetic",mode:"At home",area:"Miami-Dade",price:100,standardPrice:100,duration:"45 min",rating:4.9,reviews:66,next:"Today · 5:00 PM",description:"A gentle facial massage using deliberate movements for a relaxing personal-care experience. Individual experiences vary; Salu makes no guaranteed cosmetic or medical claims."},
 {id:"dexa",name:"DEXA Body-Composition Appointment",providerId:"baseline",provider:"Baseline Miami",category:"Preventive",mode:"Provider location",area:"Midtown",price:135,standardPrice:150,duration:"30 min",rating:4.8,reviews:79,next:"Tuesday · 10:30 AM",description:"Body-composition measurement with educational result review."},
 {id:"recovery",name:"Recovery Studio Circuit",providerId:"stillpoint",provider:"Stillpoint Recovery Club",category:"Recovery",mode:"Provider location",area:"Wynwood",price:95,standardPrice:110,duration:"75 min",rating:4.8,reviews:134,next:"Today · 6:15 PM",description:"A reservable studio session with multiple self-directed recovery amenities."},
 {id:"derm",name:"Dermatology Consultation",providerId:"luma-derm",provider:"Luma Dermatology",category:"Clinical wellness",mode:"Provider location",area:"Design District",price:295,standardPrice:325,duration:"40 min",rating:4.9,reviews:69,next:"Wednesday · 1:00 PM",description:"A consultation delivered by an independent appropriately licensed dermatology provider.",clinical:true},
 {id:"house-call",name:"Concierge Primary-Care House Call",providerId:"bay-house",provider:"Bay House Health",category:"Clinical wellness",mode:"At home",area:"Miami-Dade",price:350,standardPrice:395,duration:"60 min",rating:4.8,reviews:31,next:"Today · 7:00 PM",description:"A non-emergency house call delivered by an independent qualified clinician.",clinical:true},
 {id:"sleep",name:"At-Home Sleep-Test Setup",providerId:"rested",provider:"Rested Miami",category:"Sleep",mode:"At home",area:"Miami-Dade",price:210,standardPrice:235,duration:"45 min",rating:4.7,reviews:27,next:"Wednesday · 6:00 PM",description:"Setup assistance through an independent qualified sleep-testing partner.",clinical:true},
 {id:"facial",name:"Facial",providerId:"luma-mobile",provider:"Luma Mobile Skin",category:"Aesthetic",mode:"At home",area:"Miami-Dade",price:150,standardPrice:150,duration:"60 min",rating:4.9,reviews:143,next:"Thursday · 3:00 PM",description:"A customized facial delivered at home by an independent personal-care provider."}
];

export const topProviders:ProviderProfile[]=[
 {id:"sofia-alvarez",name:"Sofia Alvarez",initials:"SA",credential:"LMT · prototype",focuses:["Deep tissue massage","Lymphatic drainage massage"],funFact:"Trains for sunrise half marathons.",years:9,area:"Brickell",rating:4.9,reviews:128,next:"Today · 6:00 PM",serviceId:"deep-tissue",
  bio:"Nine years of deep tissue and lymphatic work with Brickell's runners and desk-bound founders. Firm, precise pressure — she reads a shoulder the way a trainer reads a split time.",
  availability:[{dayOfWeek:1,start:"09:00",end:"14:00"},{dayOfWeek:2,start:"09:00",end:"14:00"},{dayOfWeek:3,start:"16:00",end:"21:00"},{dayOfWeek:4,start:"16:00",end:"21:00"},{dayOfWeek:6,start:"10:00",end:"15:00"}]},
 {id:"mateo-ruiz",name:"Mateo Ruiz",initials:"MR",credential:"LMT · prototype",focuses:["Sports massage","Assisted stretching"],funFact:"Never misses a Miami Heat game.",years:7,area:"Miami Beach",rating:4.9,reviews:116,next:"Tomorrow · 7:30 PM",serviceId:"sports-massage",
  bio:"Sports recovery is Mateo's whole world — pre-game activation, post-training flush, and the assisted stretching that keeps South Beach's runners honest. Expect a plan, not just a rub.",
  availability:[{dayOfWeek:1,start:"17:00",end:"21:00"},{dayOfWeek:2,start:"17:00",end:"21:00"},{dayOfWeek:3,start:"17:00",end:"21:00"},{dayOfWeek:4,start:"17:00",end:"21:00"},{dayOfWeek:6,start:"09:00",end:"13:00"}]},
 {id:"elena-torres",name:"Elena Torres",initials:"ET",credential:"Stretch practitioner · prototype",focuses:["Assisted stretching","Runner recovery"],funFact:"Collects vintage running posters.",years:6,area:"Brickell",rating:4.9,reviews:94,next:"Tomorrow · 8:00 PM",serviceId:"stretch",
  bio:"A former collegiate runner who treats mobility like a skill. Elena's assisted stretching sessions are quiet, methodical, and oddly addictive — hamstrings included.",
  availability:[{dayOfWeek:1,start:"07:00",end:"12:00"},{dayOfWeek:3,start:"07:00",end:"12:00"},{dayOfWeek:5,start:"07:00",end:"12:00"},{dayOfWeek:6,start:"09:00",end:"13:00"}]},
 {id:"camila-costa",name:"Camila Costa",initials:"CC",credential:"RN · prototype",focuses:["Blood tests","Mobile specimen collection"],funFact:"Grows key limes on her balcony.",years:8,area:"Coral Gables",rating:4.8,reviews:83,next:"Monday · 8:00 AM",serviceId:"blood-draw",
  bio:"Eight years as an ER nurse before she traded the hospital for house calls. Camila runs a calm, painless blood draw — coffee's optional, punctuality isn't.",
  availability:[{dayOfWeek:1,start:"07:00",end:"11:00"},{dayOfWeek:2,start:"07:00",end:"11:00"},{dayOfWeek:3,start:"07:00",end:"11:00"},{dayOfWeek:4,start:"07:00",end:"11:00"},{dayOfWeek:5,start:"07:00",end:"11:00"}]},
 {id:"jordan-ellis",name:"Jordan Ellis",initials:"JE",credential:"RN · prototype",focuses:["IV drip","NAD+ drip"],funFact:"Makes a perfect Cuban coffee.",years:10,area:"Miami Beach",rating:4.9,reviews:79,next:"Today · 4:45 PM",serviceId:"iv",
  bio:"A decade of infusion nursing, now mobile. Jordan sets up a clean, unhurried IV visit at your home — the rare clinician who explains everything twice without being asked.",
  availability:[{dayOfWeek:1,start:"12:00",end:"18:00"},{dayOfWeek:2,start:"12:00",end:"18:00"},{dayOfWeek:4,start:"12:00",end:"18:00"},{dayOfWeek:5,start:"12:00",end:"18:00"},{dayOfWeek:6,start:"10:00",end:"15:00"}]},
 {id:"valentina-mora",name:"Valentina Mora",initials:"VM",credential:"Acupuncture physician · prototype",focuses:["Acupuncture","Recovery routines"],funFact:"Plays classical guitar.",years:12,area:"Coconut Grove",rating:5,reviews:74,next:"Friday · 4:00 PM",serviceId:"acupuncture",
  bio:"Twelve years of acupuncture practice, trained in both classical and orthopedic styles. Valentina's home sessions are slow medicine — needle, breath, quiet, repeat.",
  availability:[{dayOfWeek:2,start:"10:00",end:"15:00"},{dayOfWeek:4,start:"10:00",end:"15:00"},{dayOfWeek:5,start:"10:00",end:"17:00"}]},
 {id:"anais-laurent",name:"Anaïs Laurent",initials:"AL",credential:"LMT · prototype",focuses:["Lymphatic drainage massage","Prenatal massage"],funFact:"Speaks three languages.",years:11,area:"Key Biscayne",rating:4.9,reviews:71,next:"Tomorrow · 3:30 PM",serviceId:"lymphatic-massage",
  bio:"Trained in Paris, settled in Key Biscayne. Anaïs specializes in gentle lymphatic drainage and prenatal bodywork — the kind of session people describe as 'floating.'",
  availability:[{dayOfWeek:1,start:"10:00",end:"15:00"},{dayOfWeek:3,start:"10:00",end:"15:00"},{dayOfWeek:5,start:"10:00",end:"15:00"}]},
 {id:"marisol-vega",name:"Marisol Vega",initials:"MV",credential:"Esthetician · prototype",focuses:["Facial workout massage","Skincare rituals"],funFact:"Keeps a sketchbook of Miami doors.",years:8,area:"Design District",rating:4.9,reviews:68,next:"Today · 5:00 PM",serviceId:"facial-workout",
  bio:"Marisol treats the face like an athlete treats a muscle group. Her facial workout massage is sculptural and precise — eight years of reading skin like a map.",
  availability:[{dayOfWeek:2,start:"16:00",end:"20:00"},{dayOfWeek:3,start:"16:00",end:"20:00"},{dayOfWeek:4,start:"16:00",end:"20:00"},{dayOfWeek:6,start:"10:00",end:"14:00"}]},
 {id:"daniel-kim",name:"Daniel Kim",initials:"DK",credential:"LMT · prototype",focuses:["Sports massage","Runner recovery"],funFact:"Surfs before his first appointment.",years:6,area:"Wynwood",rating:4.9,reviews:65,next:"Saturday · 10:00 AM",serviceId:"sports-massage",
  bio:"Surf at dawn, sports massage by nine. Daniel works with Wynwood's lifters and weekend warriors — deep work, honest communication, zero small talk required.",
  availability:[{dayOfWeek:2,start:"08:00",end:"13:00"},{dayOfWeek:4,start:"08:00",end:"13:00"},{dayOfWeek:6,start:"09:00",end:"14:00"},{dayOfWeek:0,start:"10:00",end:"14:00"}]},
 {id:"gabriela-cruz",name:"Gabriela Cruz",initials:"GC",credential:"LMT · prototype",focuses:["Deep tissue massage","Lymphatic drainage massage"],funFact:"Bakes guava pastries on Sundays.",years:13,area:"Coconut Grove",rating:4.8,reviews:63,next:"Friday · 6:30 PM",serviceId:"deep-tissue",
  bio:"Thirteen years in, Gabriela still treats every back like her first. Deep tissue with a therapist's patience — she'll find the knot you stopped noticing years ago.",
  availability:[{dayOfWeek:1,start:"16:00",end:"21:00"},{dayOfWeek:3,start:"16:00",end:"21:00"},{dayOfWeek:5,start:"16:00",end:"21:00"}]},
 {id:"noah-bennett",name:"Noah Bennett",initials:"NB",credential:"Stretch practitioner · prototype",focuses:["Assisted stretching","Mobility"],funFact:"Has completed three triathlons.",years:5,area:"Miami Beach",rating:4.9,reviews:60,next:"Thursday · 7:00 PM",serviceId:"stretch",
  bio:"Three triathlons taught Noah what tight hips cost. Now he spends his evenings untying other people's — methodical assisted stretching with a coach's eye.",
  availability:[{dayOfWeek:2,start:"17:00",end:"21:00"},{dayOfWeek:4,start:"17:00",end:"21:00"},{dayOfWeek:6,start:"09:00",end:"13:00"}]},
 {id:"lucia-romero",name:"Lucia Romero",initials:"LR",credential:"RN · prototype",focuses:["Blood tests","Mobile specimen collection"],funFact:"Knows every orchid at Fairchild.",years:9,area:"Pinecrest",rating:4.8,reviews:58,next:"Tuesday · 7:30 AM",serviceId:"blood-draw",
  bio:"Nine years of pediatric and family nursing made Lucia the steadiest hands in Pinecrest. Early-morning draws, zero drama, results handled like they matter.",
  availability:[{dayOfWeek:2,start:"06:30",end:"10:30"},{dayOfWeek:4,start:"06:30",end:"10:30"},{dayOfWeek:6,start:"07:00",end:"11:00"}]},
 {id:"maya-singh",name:"Maya Singh",initials:"MS",credential:"RN · prototype",focuses:["NAD+ drip","IV drip"],funFact:"Is learning salsa dancing.",years:7,area:"Brickell",rating:4.9,reviews:55,next:"Tomorrow · 5:30 PM",serviceId:"nad",
  bio:"Maya ran infusion clinics before going mobile. Her NAD+ visits are clinical-grade but warm — vitals, screening, and a nurse who actually stays nearby.",
  availability:[{dayOfWeek:1,start:"14:00",end:"19:00"},{dayOfWeek:3,start:"14:00",end:"19:00"},{dayOfWeek:5,start:"14:00",end:"19:00"}]},
 {id:"isabelle-chen",name:"Isabelle Chen",initials:"IC",credential:"Acupuncture physician · prototype",focuses:["Acupuncture","Recovery routines"],funFact:"Has a rescue greyhound named Fig.",years:14,area:"Coral Gables",rating:4.9,reviews:52,next:"Saturday · 1:00 PM",serviceId:"acupuncture",
  bio:"Fourteen years, thousands of needles. Isabelle blends classical acupuncture with modern pain science — Coral Gables' quiet answer to chronic tension.",
  availability:[{dayOfWeek:1,start:"11:00",end:"16:00"},{dayOfWeek:3,start:"11:00",end:"16:00"},{dayOfWeek:6,start:"11:00",end:"15:00"}]},
 {id:"olivia-santos",name:"Olivia Santos",initials:"OS",credential:"LMT · prototype",focuses:["Lymphatic drainage massage","Facial massage"],funFact:"Designs tiny ceramic planters.",years:10,area:"Edgewater",rating:4.8,reviews:49,next:"Friday · 2:30 PM",serviceId:"lymphatic-massage",
  bio:"Olivia's touch is famously light — ten years of lymphatic and facial massage that leaves Edgewater regulars glowing. De-puffing is her love language.",
  availability:[{dayOfWeek:2,start:"09:00",end:"14:00"},{dayOfWeek:5,start:"09:00",end:"14:00"},{dayOfWeek:6,start:"09:00",end:"13:00"}]},
 {id:"eva-delgado",name:"Eva Delgado",initials:"ED",credential:"Esthetician · prototype",focuses:["Facial","Skincare rituals"],funFact:"Can name every beach in Miami.",years:6,area:"Miami Beach",rating:4.9,reviews:47,next:"Thursday · 4:30 PM",serviceId:"facial",
  bio:"Six years of facials, zero upsells. Eva builds a ritual around your skin — cleanse, treat, calm — and sends you home with a plan, not a product shelf.",
  availability:[{dayOfWeek:2,start:"15:00",end:"19:00"},{dayOfWeek:4,start:"15:00",end:"19:00"},{dayOfWeek:0,start:"10:00",end:"15:00"}]},
 {id:"andre-collins",name:"Andre Collins",initials:"AC",credential:"LMT · prototype",focuses:["Sports massage","Deep tissue massage"],funFact:"Coaches youth soccer on weekends.",years:8,area:"Brickell",rating:4.8,reviews:45,next:"Sunday · 11:00 AM",serviceId:"sports-massage",
  bio:"A former D1 athlete who traded the field for the table. Andre's sports massage is all function — Brickell's lifters book him before they book their trainer.",
  availability:[{dayOfWeek:0,start:"09:00",end:"14:00"},{dayOfWeek:2,start:"17:00",end:"21:00"},{dayOfWeek:4,start:"17:00",end:"21:00"}]},
 {id:"nina-park",name:"Nina Park",initials:"NP",credential:"LMT · prototype",focuses:["Deep tissue massage","Assisted stretching"],funFact:"Runs a monthly book club.",years:12,area:"South Beach",rating:4.9,reviews:42,next:"Tomorrow · 6:00 PM",serviceId:"deep-tissue",
  bio:"Twelve years of deep tissue with a stretch therapist's finish. Nina closes every session with assisted mobility work — South Beach's two-for-one secret.",
  availability:[{dayOfWeek:1,start:"17:00",end:"21:00"},{dayOfWeek:3,start:"17:00",end:"21:00"},{dayOfWeek:6,start:"10:00",end:"14:00"}]},
 {id:"tomas-herrera",name:"Tomas Herrera",initials:"TH",credential:"Stretch practitioner · prototype",focuses:["Assisted stretching","Mobility"],funFact:"Makes fresh pasta from scratch.",years:5,area:"Doral",rating:4.8,reviews:39,next:"Saturday · 9:00 AM",serviceId:"stretch",
  bio:"Tomas treats stiffness like a puzzle. Five years of assisted stretching and mobility coaching for Doral's desk workers — slow, thorough, surprisingly fun.",
  availability:[{dayOfWeek:1,start:"08:00",end:"12:00"},{dayOfWeek:3,start:"08:00",end:"12:00"},{dayOfWeek:6,start:"08:00",end:"12:00"}]},
 {id:"zoe-martin",name:"Zoe Martin",initials:"ZM",credential:"RN · prototype",focuses:["IV drip","NAD+ drip"],funFact:"Carries a film camera everywhere.",years:9,area:"Key Biscayne",rating:4.9,reviews:36,next:"Today · 7:00 PM",serviceId:"iv",
  bio:"Nine years of critical-care nursing, now doing house calls with an IV bag and a film camera. Zoe's visits are precise, calm, and weirdly photogenic.",
  availability:[{dayOfWeek:2,start:"16:00",end:"20:00"},{dayOfWeek:4,start:"16:00",end:"20:00"},{dayOfWeek:5,start:"16:00",end:"20:00"}]}
];

export const packages:PackageProduct[]=[
 {id:"runner",name:"Runner Recovery Pack",price:800,expires:"12 months from purchase",items:[{label:"Sports Massage",count:4},{label:"Assisted Stretching",count:2}]},
 {id:"essentials",name:"Salu Essentials Pack",price:900,expires:"12 months from purchase",items:[{label:"Deep Tissue Massage",count:2},{label:"Lymphatic Drainage Massage",count:2},{label:"Acupuncture",count:2}]},
 {id:"event",name:"Looking Snatched Pack",price:400,expires:"6 months from purchase",items:[{label:"Facial",count:1},{label:"Facial Workout Massage",count:1},{label:"Lymphatic Drainage Massage",count:1}]},
 {id:"glp",name:"GLP-1 Journey Pack",price:900,expires:"12 months from purchase",items:[{label:"Blood Tests",count:4},{label:"Lymphatic Drainage Massage",count:2},{label:"Facial Workout Massage",count:2}]}
];

export const initialBookings:Booking[]=[
 {id:"b-demo-1",serviceId:"sports-massage",serviceName:"Sports Massage",provider:"Tide & Tone Recovery",date:"Tomorrow · 7:30 PM",mode:"At home · Miami Beach",credits:0,status:"Upcoming",packageName:"Runner Recovery Pack",packageItem:"Sports Massage"},
 {id:"b-demo-3",serviceId:"lymphatic-massage",serviceName:"Lymphatic Drainage Massage",provider:"Tide & Tone Recovery",date:"Friday · 3:30 PM",mode:"At home · Miami-Dade",credits:120,status:"Upcoming",assignment:"proposed",proposedDate:"Friday · 8:00 PM"},
 {id:"b-demo-2",serviceId:"pilates",serviceName:"Private Pilates",provider:"Casa Forma",date:"July 28 · 9:00 AM",mode:"Provider location · Coconut Grove",credits:120,status:"Completed"}
];

export const atlasReplies=[
 {match:/protein/i,text:"Protein needs vary with body size, age, activity and health context. A common educational range for active adults is roughly 1.2–1.6 g/kg/day, spread across meals, but a registered dietitian can personalize this safely. I can find one if you’d like."},
 {match:/puffy|dehydrat|flight|travel/i,text:"After travel, reasonable first steps include sipping fluids gradually, gentle movement, a familiar balanced meal and rest. I won’t assume you need an IV. Severe or one-sided swelling, chest pain, fainting or breathing trouble needs urgent medical evaluation."},
 {match:/weight|muscle|glp/i,text:"After substantial weight loss, general support may include a registered dietitian, qualified strength professional, body-composition tracking and your own clinician. I can coordinate those categories without recommending medication or diagnosing a condition."},
 {match:/wedding|event/i,text:"Let’s work backward from the date and avoid last-minute experimentation. I can build a calm plan using personal training, a facial, massage and appropriately delivered teeth whitening."},
 {match:/emergency|chest pain|can.t breathe|faint/i,text:"This could need urgent professional attention. Atlas can’t assess emergencies. Call 911 or seek emergency care now; don’t use a wellness booking as a substitute."}
];
