export type ID = string;
export type AuthProvider = "google"|"apple"|"chatgpt"|"development"|"credentials";
export type MembershipStatus = "none"|"incomplete"|"active"|"past_due"|"canceled"|"trialing";
export type PlanName = "Member"|"Gold"|"Platinum";
export type Member={id:ID;email:string;displayName:string;householdId?:ID;planId:ID;authProvider?:AuthProvider;image?:string;createdAt?:string;stripeCustomerId?:string;stripeSubscriptionId?:string;membershipStatus?:MembershipStatus};
export type PaymentMethod={brand:string;last4:string;expMonth:number;expYear:number};
export type PaymentsSurface={stripe:boolean;goldPrice:boolean;platinumPrice:boolean;webhook:boolean;publishable:boolean;connect?:boolean};
export type PaymentsPort={getDefaultPaymentMethod(memberId:ID):Promise<PaymentMethod|null>};
export type ConnectStatus="not_connected"|"pending"|"payouts_enabled";
export type Household={id:ID;name:string;memberIds:ID[];walletId:ID};
export type MembershipPlan={id:ID;name:PlanName;monthlyContribution:number;discountPercent:0|10|20;creditsRollOver:boolean;householdSlots:number};
export type Wallet={id:ID;householdId:ID;availableCredits:number};
export type CreditTransaction={id:ID;walletId:ID;kind:"contribution"|"booking"|"refund"|"adjustment"|"topup";credits:number;createdAt:string;bookingId?:ID;label?:string;stripeEventId?:string;stripeObjectId?:string};
export type Provider={
  id:ID;
  name:string;
  email?:string;
  memberId?:ID;
  status:"demo"|"pending"|"approved";
  commissionRate:number;
  stripeConnectAccountId?:string;
  connectStatus:ConnectStatus;
  chargesEnabled?:boolean;
  payoutsEnabled?:boolean;
  detailsSubmitted?:boolean;
};
export type ProviderApplicationStatus="submitted"|"under_review"|"approved"|"rejected";
export type ProviderLicenseType="LMT"|"RN"|"Acupuncture Physician"|"Esthetician"|"Stretch practitioner"|"Other";
export type ProviderDocStatus="missing"|"received";
export type ProviderApplication={
  id:ID;
  fullName:string;
  email:string;
  phone?:string;
  licenseType:ProviderLicenseType;
  licenseNumber:string;
  mobileAtHome:boolean;
  neighborhoods:string[];
  rateAsk:string;
  insuranceAttested:boolean;
  docsLicenseProof:ProviderDocStatus;
  docsInsurance:ProviderDocStatus;
  notes?:string;
  status:ProviderApplicationStatus;
  reviewNote?:string;
  createdAt:string;
  updatedAt:string;
};
export type ProviderAccountStatus="demo"|"approved";
export type ProviderAccount={
  id:ID;
  memberId?:ID;
  email:string;
  displayName:string;
  practiceId:string;
  practiceName:string;
  status:ProviderAccountStatus;
  serviceIds:string[];
  createdAt:string;
  updatedAt:string;
};
export type AppointmentRequestStatus="open"|"accepted"|"declined"|"proposed"|"cancelled"|"assigned";
export type AppointmentRequest={
  id:ID;
  bookingId:ID;
  memberId:ID;
  memberDisplayName:string;
  serviceId:string;
  serviceName:string;
  practiceId:string;
  practiceName:string;
  date:string;
  mode:string;
  creditsCharged:number;
  status:AppointmentRequestStatus;
  assignedProviderId?:ID;
  proposedDate?:string;
  note?:string;
  walkthrough?:boolean;
  createdAt:string;
  updatedAt:string;
};
export type ProviderAssignment={
  id:ID;
  requestId:ID;
  bookingId:ID;
  providerId:ID;
  practiceId:string;
  status:"accepted"|"declined"|"proposed";
  proposedDate?:string;
  createdAt:string;
};
export type ProviderBlock={
  id:ID;
  providerId:ID;
  practiceId:string;
  date:string;
  note?:string;
  createdAt:string;
};
export type BookingAssignment="unassigned"|"accepted"|"proposed"|"declined"|"assigned";
export type ProviderCredential={id:ID;providerId:ID;label:string;status:"prototype"|"pending_review"|"verified"};
export type Service={id:ID;providerId:ID;name:string;mode:"home"|"virtual"|"location";standardPrice:number;memberPrice:number};
export type AppointmentAvailability={id:ID;serviceId:ID;startsAt:string;status:"open"|"held"|"booked"};
export type BookingStatus="held"|"confirmed"|"completed"|"cancelled";
export type Booking={
  id:ID;
  memberId:ID;
  serviceId:ID;
  availabilityId?:ID;
  status:BookingStatus;
  creditsCharged:number;
  serviceName:string;
  provider:string;
  providerId?:ID;
  date:string;
  startsAt?:string;
  slotEnd?:string;
  mode:string;
  packageName?:string;
  packageItem?:string;
  assignment?:BookingAssignment;
  proposedDate?:string;
  orgId?:ID;
  recipientName?:string;
  recipientRoom?:string;
  /** Where the booking was made: "web" (default) or "mcp" (member's AI assistant). */
  source?:string;
  createdAt:string;
  updatedAt:string;
};
export type PlatformCommission={bookingId:ID;rate:number;amount:number};
export type ProviderPayoutStatus="estimated"|"scheduled"|"paid"|"failed";
export type ProviderPayout={
  id:ID;
  bookingId:ID;
  providerId:ID;
  grossAmount:number;
  commissionAmount:number;
  netPayout:number;
  status:ProviderPayoutStatus;
  stripeTransferId?:string;
};
export type Package={id:ID;name:string;priceCredits:number;expiresAfterDays:number};
export type PackagePurchase={id:ID;packageId:ID;memberId:ID;purchasedAt:string;expiresAt:string};
export type PackageEntitlement={id:ID;purchaseId:ID;serviceCategory:string;granted:number;remaining:number};
export type Promotion={id:ID;title:string;discountPercent:number;startsAt:string;endsAt:string};
export type ConnectedApp={id:ID;memberId:ID;provider:"runna"|"strava"|"apple_health"|"garmin"|"oura"|"whoop"|"calendar";status:"demo"|"connected"|"disconnected"};
export type TrainingPlan={id:ID;memberId:ID;goal:string;raceDate:string;weeklyMileage:number;phase:string;upcomingWorkouts:{date:string;label:string}[]};
export type AtlasConversation={id:ID;memberId:ID;messages:{role:"member"|"atlas";content:string;createdAt:string}[]};
export type AtlasToolName="discover_services"|"check_availability"|"create_booking";
export type AtlasRecommendation={id:ID;conversationId:ID;serviceIds:ID[];rationale:string;safetyEscalation?:string;bookingId?:ID};
export type TravelProfile={id:ID;memberId:ID;destination:string;hotel:string;arrival:string;departure:string;goal:string;radiusMiles:number;preferredTime:string};
